### ISSUE TITLE
Mod installation failed

### ISSUE THREAD

**Issue by florianc63** [Metziell/RealTime#1]
Hello,

First of all thank you for the work!

I tried installing from your Mod Release foldera in both mod paths - C:\games\Cities Skylines Sunset Harbor\Files\Mods and C:\Users\[User]\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods

I tried different things - renaming the folder to RealTimeOffline (like the .dll file), renaming the dll file to RealTime.dll and the folder to match, leaving the folder as "Mod Release" and the mod shows "Something went very wrong" in the options tab.

Game version is 1.13.0-f8, sunset harbor
Other mods I have installed (but disabled) - ultimate eyecandy, moveIt, Fine Road Anarchy, Fine Road Tool, Dynamic Resolution and some Unlimited bla things.

Appreciate the time,
Thank you,
Florian

**Comment by Metziell** [comment]
Did you put the mod files to folder named 1749971558? It's mentioned on the RealTimeOffline Steam Workshop site.
In other words, the contents of Mod Release should be in c:\Users\\[User]\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\1749971558\.

**Comment by florianc63** [comment]
Ah, I missed that!

It's working, thank you very much, you are an awesome person.

Regards,
Florian

**Comment by Metziell** [comment]
No problem, glad to hear that.
